#163519231 Social Share components
andela/ah-jumanji-frontend pull request #27
Opened 2019-01-29 15:07 UTC by fabischolasi

#### What does this PR do?
   - This PR displays social share components on every article that is created
   - This should allow users to share the articles with their social sites

#### Description of Task to be completed?

#### How should this be manually tested?
1. Run the following commands in Terminal:
```
    git clone https://github.com/andela/ah-jumanji-frontend.git
    git checkout ft-create-social-media-components-163519231
    touch .env
```
2.  Edit the `.env` by adding this:
```
BASE_URL=https://ah-jumanji-staging.herokuapp.com
```
3. Continue in Terminal
```
    npm i && npm audit fix && npm start
```
4. After logging in, click on the `More ...` button on an article to view the icons

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#163519231](https://www.pivotaltracker.com/story/show/163519231)

#### Screenshots (if appropriate)
<img width="1280" alt="screenshot 2019-01-29 at 19 22 32" src="https://user-images.githubusercontent.com/28791783/51923091-4e5d1f80-23fb-11e9-9ccb-6d0832c5f17a.png">

#### Questions:

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] At least 2 people have reviewed my PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My PR has one commit.

2019-01-29 15:35 UTC, GransonO approved these changes
Looks good. Adds no issues to the current repo state. However, some styling would make it better. Colored icons would be it

2019-01-29 15:56 UTC, ghost requested changes
![image](https://user-images.githubusercontent.com/45358371/51920807-25d32680-23f7-11e9-87f9-fe4094b0d75a.png)

I think this would look better if we:
1. restyle the icons so that they match the sites they represent (i.e., use `Facebook's blue` for the Facebook icon, and etc)
2. convert the icons into `anchor tags (links)`. They are after all pointers to other sites.
`OR, instead of 2. above,`
use `css` to change the cursor to a `pointer` when a user hovers over the icons.

2019-01-29 16:21 UTC, fabischolasi commented
> ![image](https://user-images.githubusercontent.com/45358371/51920807-25d32680-23f7-11e9-87f9-fe4094b0d75a.png)
> 
> I think this would look better if we:
> 
> 1. restyle the icons so that they match the sites they represent (i.e., use `Facebook's blue` for the Facebook icon, and etc)
> 2. convert the icons into `anchor tags (links)`. They are after all pointers to other sites.
>    `OR, instead of 2. above,`
>    use `css` to change the cursor to a `pointer` when a user hovers over the icons.

This has been resolved

2019-01-29 16:43 UTC, EmmanuelBeja reviewed
could you center the icons and have two <hr> tags enclosing them.

2019-01-29 17:12 UTC, ghost approved these changes
👍

2019-01-29 19:03 UTC, fabischolasi commented
> could you center the icons and have two
> 
> tags enclosing them.

What tags

2019-01-29 19:07 UTC, fabischolasi commented
> could you center the icons and have two
> 
> tags enclosing them.

Would centring the articles look nice really? That would mean I have to centre the *Share Article*  title too

2019-01-30 06:25 UTC, EmmanuelBeja commented
> > could you center the icons and have two
> > tags enclosing them.
> 
> Would centring the articles look nice really? That would mean I have to centre the _Share Article_ title too of which I don't think is a nice idea

This is what i had in mind.

<img width="352" alt="screen shot 2019-01-30 at 09 23 53" src="https://user-images.githubusercontent.com/19776238/51962355-e5b08a00-2470-11e9-9bfe-e9238ebb44b8.png">

2019-01-30 06:27 UTC, EmmanuelBeja commented on src/apps/SocialShare/components/SocialShareIcons.js
> +        <div className="dropdown-item more btn-link" data-toggle="modal" data-target="#social-icons">
You should remove the code:
data-toggle="modal" data-target="#social-icons"

it is meant for modals.

2019-01-31 07:39 UTC, closed without merging